[project]
name = 'polarion_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.anonymization]
path = 'contracts/anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.ress]
path = 'contracts/ress.clar'
clarity_version = 2
epoch = 2.5

[contracts.tokenized_governance]
path = 'contracts/tokenized_governance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
